manager: Disallow NULL string in custom core location on manager page
Before this patch, on the manager page if you accidentally click
"Create vmcore task" without typing anything into the "Custom
core location" box a task will be created and immediately fail
with a message similar to the following:
[2021-10-11 22:39:11] [I] Downloading remote resources
[2021-10-11 22:39:11] [I] Retrieving remote file ''
[2021-10-11 22:39:11] [W] malformed URL
[2021-10-11 22:39:11] [W] No files found in the tarball
[2021-10-11 22:39:11] [I] Analyzing crash data
[2021-10-11 22:39:11] [E] Task failed: Crash directory does not contain required file 'vmcore'
[2021-10-11 22:39:11] [D] Backtrace: Crash directory does not contain required file 'vmcore'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/retrace/retrace_worker.py", line 1123, in start
    raise Exception("Crash directory does not contain required file '%s'" % required_file)
Exception: Crash directory does not contain required file 'vmcore'

This patch fixes the above by checking for a 0 length string in
the custom_url, and returns a 400 error with the message
"URL cannot be NULL string", rather than creating a task which
always fails.

Signed-off-by: Dave Wysochanski <dwysocha@redhat.com>