Fix backtrace of bt_filter on Python3
Since moving to Python3 bt_filter has been backtracing as follows.
version: 0.8

Traceback (most recent call last):
  File "/usr/bin/bt_filter", line 226, in <module>
    main()
  File "/usr/bin/bt_filter", line 218, in main
    backtrace_file_parser(input, bt_hash, bt_proc)
  File "/usr/bin/bt_filter", line 128, in backtrace_file_parser
    hash = backtrace_calc_hash(proc_backtrace)
  File "/usr/bin/bt_filter", line 99, in backtrace_calc_hash
    hash = sha(''.join(proc_backtrace))
TypeError: Unicode-objects must be encoded before hashing

Signed-off-by: Dave Wysochanski <dwysocha@redhat.com>