Fix backtrace when updating bugzillano from web UI due to use of basestring
Python3 no longer has 'basestring' class but instead 'str' should be used.
https://docs.python.org/3.0/whatsnew/3.0.html

Use of 'basestring' in set_bugzillano causes the following backtrace:
Traceback (most recent call last):
  File "/usr/share/retrace-server/manager.wsgi", line 228, in application
    task.set_bugzillano(bugzillano)
  File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 2358, in set_bugzillano
    if not isinstance(values, list) or not all([isinstance(v, str) for v in values]):
  File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 2358, in <listcomp>
    if not isinstance(values, list) or not all([isinstance(v, str) for v in values]):
NameError: name 'basestring' is not defined

Signed-off-by: Dave Wysochanski <dwysocha@redhat.com>