Set "crash" inside get_crash_cmd file if the file does not exist, fix get_use_mock typeo.
This patch fixes a couple oversights in the previous patcheset to introduce crash_cmd and use_mock.

First, for older tasks which do not have a 'crash_cmd' file, we need to create one by
default.  Otherwise, any retrace-server-worker or retrace-server-interact command may
fail as follows:
Traceback (most recent call last):
  File "/usr/bin/retrace-server-interact", line 117, in <module>
    crash_cmd = task.get_crash_cmd().split()
AttributeError: 'NoneType' object has no attribute 'split'

Second, retrace-server-interact contained a 'get_use_mock' function rather than 'use_mock'
This caused the following:
$ retrace-server-interact 757071668 shell
Traceback (most recent call last):
  File "/usr/bin/retrace-server-interact", line 138, in <module>
    if task.get_use_mock(kernelver):
AttributeError: RetraceTask instance has no attribute 'get_use_mock'

Signed-off-by: Dave Wysochanski <dwysocha@redhat.com>